### ISSUE TITLE
Process is killed after await mvn.execute

### ISSUE THREAD

**Issue by DiabolusExMachina** [headcr4sh/node-maven#17]
Hello, 

I was planning to use this library in a jest integration test. My idea was to start my backend perform tests and stop the backend. At first everything looks good. The backend starts, and the test begin. However the backend is stopped again before the tests begin. 

This is the code I use

```javascript
beforeAll(async () => {
  jasmine.DEFAULT_TIMEOUT_INTERVAL = 15000;
  await mvn.execute("spring-boot:start"); //backend starts up
  //process is gone, all tests fail :-( 
});

it('renders without crashing', async (done) => {
//...
}

afterAll(async () => {
  await mvn.execute("spring-boot:stop");
});
```

and this the documentation of the springboot plugin
https://docs.spring.io/spring-boot/docs/current/maven-plugin/plugin-info.html

I'm on Windows

**Comment by DiabolusExMachina** [comment]
ok sorry my fault this also happen in my console. this can be closed

**Comment by headcr4sh** [comment]
Ok. Closing the issue. ;-)
