### ISSUE TITLE
Support for -ntp/--no-transfer-progress

### ISSUE THREAD

**Issue by natami** [headcr4sh/node-maven#20]
Is there a possibility to add support for --no-transfer-progress/-ntp in MavenOptions?

Kindly regards.

**Comment by headcr4sh** [comment]
Sure. If you provide a PR I'll gladly merge it.. ;-)

**Comment by headcr4sh** [comment]
Closed by #21 
Thanks, @natami.

**Comment by headcr4sh** [comment]
Version 4.6.0 (just tagged and pushed to NPM) contains the new feature.
