### ISSUE TITLE
Request for -pl or --projects option support

### ISSUE THREAD

**Issue by kaustubhgadre** [headcr4sh/node-maven#29]
I use Maven Reactors a lot and I would like to see if you can add support for --projects option to run only specific projects/modules within the reactor. 

If I have a reactor abc with the following modules:
* abc
* abc-impl
* abc-rest
* abc-test

I would like a support for running just abc-test like following. 
```
mvn clean verify -pl abc-test
```

**Comment by kaustubhgadre** [comment]
Pull request #30 is created for this.

**Comment by headcr4sh** [comment]
Thanks for the PR!
