### ISSUE TITLE
I need to report errors in gulp script. Can I rely on `execute` returning Promise in further versions of the module?

### ISSUE THREAD

**Issue by KonstantinSviridov** [headcr4sh/node-maven#4]
Hi guys.

I am running the module in a gulp script and, thus, have the need to report failures.
As the `execute` method returns Promise, I can handle it as

```
gulp.task('java:build', [],function (done) {
  var mvn = maven.create();
  return mvn.execute(['clean', 'install']).then(
      function(x){},
      function(err){
         throw new Error("Compilation failed");
      });
});
```

The `execute` return type is not documented, so I have a question: do you have plans of changing it?

Regards, Konstantin.

**Comment by headcr4sh** [comment]
I do NOT plan to change the return type.
Even though it is not (yet) documented, the API shall stay Promise-based.

**Comment by KonstantinSviridov** [comment]
Thanks!
